In [2]:
import pandas as pd

def answer_one():
    
    energy = pd.read_excel('Energy Indicators.xls',
                                skiprows = 17,
                                skipfooter = 38,
                                na_values='...') 


    energy = pd.DataFrame(energy)

    energy = energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'])
    energy.columns = (['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']) 

    energy['Energy Supply'] = energy['Energy Supply'] * 1000000

    
    energy.loc[energy['Country'] == 'Republic of Korea', 'Country'] = 'South Korea'
    energy.loc[energy['Country'] == 'United States of America', 'Country'] = 'United States' 
    energy.loc[energy['Country'] == 'United Kingdom of Great Britain and Northern Ireland', 'Country'] = 'United Kingdom' 
    energy.loc[energy['Country'] == 'China, Hong Kong Special Administrative Region', 'Country'] = 'Hong Kong' 


    energy['Country'] = (energy['Country']
                        .str.replace(r"\(.*?\)", "", regex = True)
                        .str.replace(r'\d+', '', regex=True)
                        .str.strip()
                        )


    
    GDP = pd.read_csv('API_NY.GDP.MKTP.CD_DS2_en_csv_v2_133326.csv', skiprows=4)
     
    GDP['Country Name'] = GDP['Country Name'].replace({
            'Korea, Rep.': 'South Korea',
            'Iran, Islamic Rep.': 'Iran',
            'Hong Kong SAR, China': 'Hong Kong'
        } )

    
    ScimEm = pd.read_excel("scimagojr country rank 1996-2024.xlsx")
    
    ScimEm_top15 = ScimEm[ScimEm['Rank'] <= 15]

    GDP = GDP.rename(columns={'Country Name': 'Country'})
    
    years = list(map(str, range(2006, 2016)))
    GDP = GDP[['Country'] + years]

    result = pd.merge(ScimEm_top15, energy, how='inner', on='Country')
    result = pd.merge(result, GDP, how='inner', on='Country')

    result = result.set_index('Country')

    result = result[['Rank', 'Documents', 'Citable documents',
                        'Citations', 'Self-citations',
                        'Citations per document', 'H index',
                        'Energy Supply', 'Energy Supply per Capita',
                        '% Renewable'] + years]
    return result

answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,1.271910e+11,93.0,19.754910,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
India,3,96975,94714,1243636,479638,12.82,258,3.319500e+10,26.0,14.969080,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
Japan,5,61939,61307,813472,166907,13.13,246,1.898400e+10,149.0,10.232820,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,55466,54296,932195,185376,16.81,274,1.326100e+10,165.0,17.901530,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,49938,49562,268391,112125,5.37,123,3.070900e+10,214.0,17.288680,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,44877,44004,1082361,161133,24.12,305,1.043100e+10,296.0,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,42635,40695,767280,171442,18.00,227,6.530000e+09,109.0,33.667230,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,42534,42174,761076,124789,17.89,215,1.100700e+10,221.0,2.279353,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,35889,35484,798505,211983,22.25,218,9.172000e+09,119.0,5.707721,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,33407,32698,637552,99244,19.08,235,1.059700e+10,166.0,17.020280,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,32521,31781,726414,118758,22.34,233,4.923000e+09,106.0,37.968590,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,31047,30232,760284,99637,24.49,262,5.386000e+09,231.0,11.810810,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,30840,30383,371926,84223,12.06,167,1.214900e+10,59.0,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [3]:

def answer_two():
    Top15 = answer_one()
    years = list(map(str, range(2006, 2016)))

    avgGDP = Top15[years].mean(axis= 1, skipna=True) 

    avgGDP = avgGDP.sort_values(ascending = False)
    
    return avgGDP
 
answer_two()

Country
China                 7.048894e+12
Japan                 5.239642e+12
Germany               3.590126e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.275614e+12
Australia             1.211998e+12
Iran                  4.567516e+11
dtype: float64

In [4]:

def answer_three():
    Top15 = answer_one()
    q2 = answer_two()
    d = Top15.loc[q2.index[5]]
    dif = d['2015'] - d['2006']
    
    return dif

answer_three()

np.float64(694585288293.19)

In [5]:
 
def answer_four():
    Top15 = answer_one()

    Top15['ratio'] = Top15['Self-citations'] / Top15['Citations']

    value_max = Top15['ratio'].max()

    country_max = Top15['ratio'].idxmax()

    return (country_max, value_max)


answer_four()

('China', np.float64(0.6970630544852335))

In [6]:

def answer_five():
    Top15 = answer_one()

    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
     
    country = Top15['Population'].sort_values(ascending=False).index[2]
    
    return country

answer_five()

'Brazil'

In [7]:


def answer_six():
    Top15 = answer_one()

    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
 
    Top15['documents per person'] = Top15['Citable documents'] / Top15['Population']
    
    result = Top15['documents per person'].corr(Top15['Energy Supply per Capita'])
   
    return result
 
answer_six()

np.float64(0.8046410432116898)

In [8]:

def answer_seven():
    Top15 = answer_one()

     
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    
    Top15['Continent']= Top15.index.map(ContinentDict)
     

    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    
    Top15= Top15.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std']) 
    
    return Top15


answer_seven()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            5  3.940587e+08  7.881174e+07  3.813228e+07
North America     1  3.523986e+07  3.523986e+07           NaN
South America     1  2.059153e+08  2.059153e+08           NaN